### ISSUE TITLE
XPS import?

### ISSUE THREAD

**Issue by NebuHiiEjamu** [Menithal/Blender-Hifi-Addon#17]
XNALara is a popular format, most noticeably on DeviantArt. It's not as popular as MMD, but it's still in wide use. There exists a Blender import add-on for files, so I'm wondering if Hifi tools can specialise the import?

Existing import addon is at https://www.deviantart.com/johnzero7/ plus the guy has some XPS models favorited.

**Comment by Menithal** [comment]
Going to investigate the format.
Will likely, just like MMD Format just leave the importing to the original 
plugin it self, but try handling all the bone corrections in the Hifi Plugin.

**Comment by NebuHiiEjamu** [comment]
I can give you a list of uniform bone names just like MMD has, if you want.

**Comment by Menithal** [comment]
Would be better if you gave me a list of examples, will need to test the rotations of the bones as well

**Comment by NebuHiiEjamu** [comment]
Okay well my friend on deviantArt makes plenty, and they're downloadable as well.
https://www.deviantart.com/lopieloo

Also, here's the faulty MMD model that crashes the addon It also comes in XPS format
https://www.deviantart.com/sab64/art/MMD-XPS-Model-Banjo-Kazooie-Download-671985035

**Comment by Menithal** [comment]
Regarding the Banjo Kazooie fan models that come packaged It does not follow the MMD skeleton naming at all, since its already in English.

"The crash" just happens due to it missing both Spine1 and Spine2 which I had wrongly assumed, had one or the other always exist on MMD models, especially if they are used in the MMD Suite with existing MMD animations. I will correct that mistake by reading the skeleton after the translation step and looking for them prior to trying to do mods to it.

For this, one should use a custom skeleton binding that I  (nor others) have yet to have gotten around to writing. As it is using someone else own naming convention instead of one of the standards.

**Comment by Menithal** [comment]
Moving this to 1.3 instead. First working on custom skeleton binding out of box instead of custom modules per each avatar skeleton type.

**Comment by Menithal** [comment]
Custom Skeleton Binding is now in, so it should be able to handle XPS models, as long as they have english names, otherwise it maybe a bit of a slog to rebind them in the custom skeleton binder.

Will actually move this forward to 1.4 because I think I ll focus on getting VRoid support instead as it seems to be a rising format.

**Comment by Menithal** [comment]
Going to close this now, not really a priority since hifi isnt anymore, and theoretically the skeleton converted should already handle the conversion process.

Going to focus instead of supporting VRM, which is more upcomming and probably more relevant to metaverses.
